-- MySql
CREATE SCHEMA `suntech`;
CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(100) DEFAULT NULL,
  `enabled` bit(1) NOT NULL,
  `name` varchar(50) DEFAULT NULL,
  `password` varchar(10) DEFAULT NULL,
  `phone` varchar(15) DEFAULT NULL,
  `registerdate` datetime DEFAULT NULL,
  `surname` varchar(50) DEFAULT NULL,
  `username` varchar(14) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO USER(ID,USERNAME,PASSWORD,ENABLED,REGISTERDATE,NAME,SURNAME,EMAIL,PHONE)
VALUES(1,'MY.USER','123456',1,{ts '2016-05-20 12:10:21'},'LUCAS','DE SOUZA','LUKASHEITICH@GMAIL.COM','9903-2222');

INSERT INTO USER(ID,USERNAME,PASSWORD,ENABLED,REGISTERDATE,NAME,SURNAME,EMAIL,PHONE)
VALUES(2,'FRANCISCO.FERREIRA','123456',1,{ts '2016-03-21 14:32:11'},'FRANCISCO','FERREIRA','FRANCISCO@GMAIL.COM','9903-8368');